require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BurstsController do

  def mock_burst(stubs={})
    @mock_burst ||= mock_model(Burst, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all bursts as @bursts" do
      Burst.stub(:all) { [mock_burst] }
      get :index
      assigns(:bursts).should eq([mock_burst])
    end
  end

  describe "GET show" do
    it "assigns the requested burst as @burst" do
      Burst.stub(:find).with("37") { mock_burst }
      get :show, :id => "37"
      assigns(:burst).should be(mock_burst)
    end
  end

  describe "GET new" do
    it "assigns a new burst as @burst" do
      Burst.stub(:new) { mock_burst }
      get :new
      assigns(:burst).should be(mock_burst)
    end
  end

  describe "GET edit" do
    it "assigns the requested burst as @burst" do
      Burst.stub(:find).with("37") { mock_burst }
      get :edit, :id => "37"
      assigns(:burst).should be(mock_burst)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created burst as @burst" do
        Burst.stub(:new).with({'these' => 'params'}) { mock_burst(:save => true) }
        post :create, :burst => {'these' => 'params'}
        assigns(:burst).should be(mock_burst)
      end

      it "redirects to the created burst" do
        Burst.stub(:new) { mock_burst(:save => true) }
        post :create, :burst => {}
        response.should redirect_to(burst_url(mock_burst))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved burst as @burst" do
        Burst.stub(:new).with({'these' => 'params'}) { mock_burst(:save => false) }
        post :create, :burst => {'these' => 'params'}
        assigns(:burst).should be(mock_burst)
      end

      it "re-renders the 'new' template" do
        Burst.stub(:new) { mock_burst(:save => false) }
        post :create, :burst => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested burst" do
        Burst.stub(:find).with("37") { mock_burst }
        mock_burst.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :burst => {'these' => 'params'}
      end

      it "assigns the requested burst as @burst" do
        Burst.stub(:find) { mock_burst(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:burst).should be(mock_burst)
      end

      it "redirects to the burst" do
        Burst.stub(:find) { mock_burst(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(burst_url(mock_burst))
      end
    end

    describe "with invalid params" do
      it "assigns the burst as @burst" do
        Burst.stub(:find) { mock_burst(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:burst).should be(mock_burst)
      end

      it "re-renders the 'edit' template" do
        Burst.stub(:find) { mock_burst(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested burst" do
      Burst.stub(:find).with("37") { mock_burst }
      mock_burst.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the bursts list" do
      Burst.stub(:find) { mock_burst }
      delete :destroy, :id => "1"
      response.should redirect_to(bursts_url)
    end
  end

end
